import { ENTITY_COLORS } from "../strategy-map-types";
import { RulesConfigSchema, type ModuleRule, type RulesConfig } from "./types";

/**
 * Klucze modułów health-score (sidebar). Po scaleniu taksonomii (2.1):
 * jedna lista kluczy mapy + dwa moduły bez węzła na mapie (discovery, brand).
 * Zniknęły duplikaty health (business/segments/funnel/sales/website).
 */
export const HEALTH_MODULE_KEYS = [
  "discovery",
  "brand",
  "fundament",
  "segmenty",
  "lejek",
  "kanaly",
  "przekaz",
  "sprzedaz",
  "strona",
  "kpi",
] as const;

/**
 * Domyślna konfiguracja reguł — 1:1 z dotychczasowym hardcode
 * (health-score.ts, strategy-map.ts:491–510, strategy-map-types.ts, buildInfluenceGraph).
 */
/**
 * Domyślne reguły przez `RulesConfigSchema.parse` — defaulty (`onMap`, `version`,
 * nested optional) wypełniają się tak samo jak dla configów zapisanych w DB.
 */
export const DEFAULT_RULES: RulesConfig = RulesConfigSchema.parse({
  version: 2,

  modules: [
    {
      key: "discovery",
      label: "Discovery",
      onMap: false,
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "disc_questions",
          label: "≥5 pytań discovery",
          weight: 0.5,
          metric: "count_gte",
          entity: "projectQuestions",
          target: 5,
        },
        {
          id: "disc_materials",
          label: "≥2 materiały",
          weight: 0.5,
          metric: "count_gte",
          entity: "projectMaterials",
          target: 2,
        },
      ],
      lock: { enabled: false, requiresUpstream: [] },
      stale: { enabled: false },
      visibleInClient: true,
    },
    {
      key: "brand",
      label: "Marka",
      onMap: false,
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "brand_mission",
          label: "Misja wypełniona",
          weight: 0.25,
          metric: "field_filled",
          entity: "brandIdentity",
          field: "missionMd",
        },
        {
          id: "brand_vision",
          label: "Wizja wypełniona",
          weight: 0.25,
          metric: "field_filled",
          entity: "brandIdentity",
          field: "visionMd",
        },
        {
          id: "brand_tov",
          label: "Tone of voice",
          weight: 0.25,
          metric: "field_filled",
          entity: "brandIdentity",
          field: "toneOfVoiceMd",
        },
        {
          id: "brand_visual",
          label: "Paleta wizualna",
          weight: 0.25,
          metric: "custom",
          entity: "brandVisual",
        },
      ],
      lock: { enabled: false, requiresUpstream: [] },
      stale: { enabled: false },
      visibleInClient: true,
    },
    {
      key: "fundament",
      label: "Fundament",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "fund_problems",
          label: "Problemy / ambicje",
          weight: 0.2,
          metric: "count_gte",
          entity: "businessProblems",
          target: 1,
        },
        {
          id: "fund_uvp",
          label: "UVP core",
          weight: 0.2,
          metric: "field_filled",
          entity: "uvp",
          field: "coreUvpMd",
        },
        {
          id: "fund_competitors",
          label: "Konkurencja",
          weight: 0.2,
          metric: "count_gte",
          entity: "competitors",
          target: 1,
        },
        {
          id: "fund_objections",
          label: "Obiekcje",
          weight: 0.2,
          metric: "count_gte",
          entity: "objections",
          target: 1,
        },
        {
          // B3 (logika Negacza): „jesteśmy X dla Y, którzy chcą Z, w przeciwieństwie do W".
          id: "fund_positioning",
          label: "Pozycjonowanie / specjalizacja zdefiniowane",
          weight: 0.2,
          metric: "field_filled",
          entity: "positioning",
          field: "positioningStatement",
        },
      ],
      lock: { enabled: true, requiresUpstream: [] },
      stale: { enabled: true },
      visibleInClient: true,
    },
    {
      key: "kryteria_rynku",
      label: "Kryteria segmentacji rynku",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "kryteria_dimensions",
          label: "Wymiary segmentacji zdefiniowane",
          weight: 1,
          metric: "custom",
        },
      ],
      lock: { enabled: false, requiresUpstream: [] },
      stale: { enabled: false },
      visibleInClient: false,
    },
    {
      key: "segmenty",
      label: "Segmenty",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "map_seg_count",
          label: "≥3 segmenty",
          weight: 1,
          metric: "count_gte",
          entity: "segments",
          target: 3,
        },
      ],
      lock: { enabled: true, requiresUpstream: ["fundament"] },
      stale: { enabled: true },
      visibleInClient: true,
    },
    {
      key: "lejek",
      label: "Lejek",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "lejek_stages",
          label: "Etapy podróży zakupowej",
          weight: 0.15,
          metric: "count_gte",
          entity: "purchaseStages",
          target: 1,
        },
        {
          // Gap engine (Negacz): każdy etap ma odpowiedź-treść, nie „ile elementów".
          id: "journey_content_coverage",
          label: "Każdy etap podróży ma treść",
          weight: 0.35,
          metric: "custom",
        },
        {
          id: "journey_exit_coverage",
          label: "Każdy etap ma wyjście do przodu (CTA)",
          weight: 0.2,
          metric: "custom",
        },
        {
          id: "lejek_flows",
          label: "User flows",
          weight: 0.1,
          metric: "count_gte",
          entity: "userFlows",
          target: 1,
        },
        {
          id: "lejek_cta_measurable",
          label: "CTA elementów lejka powiązane ze zdarzeniem konwersji",
          weight: 0.2,
          metric: "custom",
        },
      ],
      lock: { enabled: true, requiresUpstream: ["segmenty"] },
      stale: { enabled: true },
      visibleInClient: true,
    },
    {
      key: "kanaly",
      label: "Kanały",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "map_channels",
          label: "≥4 kanały",
          weight: 0.4,
          metric: "count_gte",
          entity: "channels",
          target: 4,
        },
        {
          id: "journey_channel_coverage",
          label: "Każdy etap podróży ma kanał dystrybucji",
          weight: 0.6,
          metric: "custom",
        },
      ],
      lock: { enabled: true, requiresUpstream: ["lejek"] },
      stale: { enabled: true },
      visibleInClient: true,
    },
    {
      key: "przekaz",
      label: "Przekaz",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "przekaz_pitches",
          label: "Pitche",
          weight: 0.25,
          metric: "count_gte",
          entity: "salesPitches",
          target: 1,
        },
        {
          id: "przekaz_scripts",
          label: "Skrypty",
          weight: 0.25,
          metric: "count_gte",
          entity: "salesScripts",
          target: 1,
        },
        {
          id: "przekaz_lead_magnets",
          label: "Lead magnety",
          weight: 0.25,
          metric: "count_gte",
          entity: "leadMagnets",
          target: 1,
        },
        {
          id: "przekaz_copy",
          label: "Wytyczne copy",
          weight: 0.25,
          metric: "custom",
          entity: "copyGuidelines",
        },
      ],
      lock: { enabled: true, requiresUpstream: ["lejek"] },
      stale: { enabled: true },
      visibleInClient: true,
    },
    {
      key: "sprzedaz",
      label: "Sprzedaż",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          // Gap engine: etapy `ownerSide=sales|shared` mają akcję handlową.
          id: "journey_sales_coverage",
          label: "Każdy etap sprzedażowy ma akcję handlową",
          weight: 0.5,
          metric: "custom",
        },
        {
          id: "sprzedaz_activities",
          label: "≥1 akcja procesu sprzedaży",
          weight: 0.25,
          metric: "count_gte",
          entity: "salesActivities",
          target: 1,
        },
        {
          id: "sprzedaz_pitches",
          label: "≥1 pitch sprzedażowy",
          weight: 0.25,
          metric: "count_gte",
          entity: "salesPitches",
          target: 1,
        },
      ],
      lock: { enabled: true, requiresUpstream: ["segmenty", "lejek"] },
      stale: { enabled: true },
      visibleInClient: false,
    },
    {
      key: "strona",
      label: "Strona",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "map_pages",
          label: "≥4 podstrony",
          weight: 1,
          metric: "count_gte",
          entity: "pages",
          target: 4,
        },
      ],
      lock: { enabled: true, requiresUpstream: ["segmenty", "lejek"] },
      stale: { enabled: true },
      visibleInClient: true,
    },
    {
      key: "kpi",
      label: "KPI",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "map_kpi_count",
          label: "≥4 wskaźniki",
          weight: 0.3,
          metric: "count_gte",
          entity: "kpis",
          target: 4,
        },
        {
          id: "kpi_measurable",
          label: "KPI powiązane ze zdarzeniem analitycznym (event_key)",
          weight: 0.3,
          metric: "custom",
        },
        {
          id: "journey_kpi_coverage",
          label: "Każdy etap podróży jest mierzony KPI",
          weight: 0.4,
          metric: "custom",
        },
      ],
      lock: { enabled: true, requiresUpstream: ["kanaly", "strona"] },
      stale: { enabled: true },
      visibleInClient: true,
    },
    {
      key: "pitche",
      label: "Pitche sprzedażowe",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "pitche_count",
          label: "≥1 pitch",
          weight: 1,
          metric: "count_gte",
          entity: "salesPitches",
          target: 1,
        },
      ],
      lock: { enabled: true, requiresUpstream: ["segmenty", "fundament"] },
      stale: { enabled: true },
      visibleInClient: false,
    },
    {
      key: "sekcje",
      label: "Sekcje podstron",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "sekcje_count",
          label: "≥1 sekcja",
          weight: 1,
          metric: "count_gte",
          entity: "pageSections",
          target: 1,
        },
      ],
      lock: { enabled: true, requiresUpstream: ["strona"] },
      stale: { enabled: true },
      visibleInClient: false,
    },
    {
      key: "seo",
      label: "SEO / słowa kluczowe",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "seo_count",
          label: "≥1 słowo kluczowe",
          weight: 1,
          metric: "count_gte",
          entity: "seoKeywords",
          target: 1,
        },
      ],
      lock: { enabled: true, requiresUpstream: ["strona"] },
      stale: { enabled: true },
      visibleInClient: false,
    },
    {
      key: "geo",
      label: "GEO / AEO (widoczność w AI)",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "geo_count",
          label: "≥1 asset GEO",
          weight: 1,
          metric: "count_gte",
          entity: "geoAssets",
          target: 1,
        },
      ],
      lock: { enabled: true, requiresUpstream: ["strona", "seo"] },
      stale: { enabled: true },
      visibleInClient: false,
    },
    {
      key: "oferta",
      label: "Oferta",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "oferta_count",
          label: "≥1 oferta",
          weight: 1,
          metric: "count_gte",
          entity: "offers",
          target: 1,
        },
      ],
      lock: { enabled: true, requiresUpstream: ["fundament", "segmenty"] },
      stale: { enabled: true },
      visibleInClient: false,
    },
    {
      key: "kampanie",
      label: "Kampanie marketingowe",
      readyThreshold: 80,
      inProgressThreshold: 1,
      criteria: [
        {
          id: "kampanie_count",
          label: "≥1 kampania",
          weight: 1,
          metric: "count_gte",
          entity: "campaigns",
          target: 1,
        },
      ],
      lock: { enabled: true, requiresUpstream: ["lejek", "kanaly", "oferta"] },
      stale: { enabled: true },
      visibleInClient: false,
    },
  ],

  connections: [
    { from: "fundament", to: "segmenty" },
    { from: "segmenty", to: "lejek" },
    { from: "lejek", to: "kanaly" },
    { from: "lejek", to: "przekaz" },
    { from: "lejek", to: "sprzedaz" },
    { from: "sprzedaz", to: "kpi" },
    { from: "segmenty", to: "strona" },
    { from: "lejek", to: "strona" },
    { from: "kanaly", to: "kpi" },
    { from: "strona", to: "kpi" },
    { from: "fundament", to: "pitche" },
    { from: "segmenty", to: "pitche" },
    { from: "strona", to: "sekcje" },
    { from: "strona", to: "seo" },
    { from: "seo", to: "geo" },
    { from: "fundament", to: "oferta" },
    { from: "segmenty", to: "oferta" },
    { from: "lejek", to: "kampanie" },
    { from: "kanaly", to: "kampanie" },
    { from: "oferta", to: "kampanie" },
  ],

  presentationOrder: [
    "fundament",
    "segmenty",
    "lejek",
    "kanaly",
    "przekaz",
    "sprzedaz",
    "strona",
    "kpi",
  ],

  correlations: [
    {
      id: "stage_element",
      sourceType: "stage",
      targetType: "element",
      label: "wywołuje",
      defaultStrength: "strong",
      required: false,
    },
    {
      id: "problem_element",
      sourceType: "problem",
      targetType: "element",
      label: "adresuje",
      defaultStrength: "normal",
      required: false,
    },
    {
      id: "objection_element",
      sourceType: "objection",
      targetType: "element",
      label: "zbija",
      defaultStrength: "weak",
      required: false,
    },
    {
      id: "goal_element",
      sourceType: "goal",
      targetType: "element",
      label: "odpowiada na",
      defaultStrength: "normal",
      required: false,
    },
    {
      id: "element_flow",
      sourceType: "element",
      targetType: "flow",
      label: "realizowany przez",
      defaultStrength: "normal",
      required: true,
    },
    {
      id: "element_seo",
      sourceType: "element",
      targetType: "seo",
      label: "targetuje",
      defaultStrength: "weak",
      required: false,
    },
    {
      id: "element_page",
      sourceType: "element",
      targetType: "page",
      label: "ląduje na",
      defaultStrength: "normal",
      required: false,
    },
    {
      id: "element_channel",
      sourceType: "element",
      targetType: "channel",
      label: "publikowany w",
      defaultStrength: "normal",
      required: false,
    },
    {
      id: "element_campaign",
      sourceType: "element",
      targetType: "campaign",
      label: "promowany przez",
      defaultStrength: "normal",
      required: false,
    },
    {
      id: "element_geo",
      sourceType: "element",
      targetType: "geo",
      label: "cytowalny w AI przez",
      defaultStrength: "normal",
      required: false,
    },
    {
      id: "element_kpi",
      sourceType: "element",
      targetType: "kpi",
      label: "mierzony przez",
      defaultStrength: "strong",
      required: true,
    },
    {
      id: "flow_page",
      sourceType: "flow",
      targetType: "page",
      label: "ląduje na",
      defaultStrength: "normal",
      required: false,
    },
    {
      id: "page_seo",
      sourceType: "page",
      targetType: "seo",
      label: "targetuje",
      defaultStrength: "weak",
      required: false,
    },
  ],

  alerts: {
    kpiBelowPct: 80,
    kpiBelowDays: 14,
    visitDays: 7,
    domainExpiringDays: 30,
    syncFailThreshold: 3,
  },

  palette: {
    ...ENTITY_COLORS,
    campaign: "#a78bfa",
    geo: "#22d3ee",
  },
});

export function findModuleRule(
  rules: RulesConfig,
  key: string
): ModuleRule | undefined {
  return rules.modules.find((m) => m.key === key);
}
